"""Server-side mock data mirroring src/mockData.ts.

- TEAMMATES / PERKS / SCHEDULE are embedded into the agent system prompts so the model
  references real IDs (the frontend renders them by ID from src/mockData.ts).
- SEED_PROFILES are the 8 candidate profiles seeded into Supabase as the match pool.
"""

TEAMMATES = [
    {"id": "t1", "name": "Alex Rivera", "role": "Dev", "experience": "Fullstack Developer",
     "tags": ["React", "TypeScript", "Node.js", "Express"], "bio": "Fullstack web + LLM APIs."},
    {"id": "t2", "name": "Susan Jones", "role": "Design", "experience": "Senior UI/UX Designer",
     "tags": ["Figma", "Prototyping", "Branding", "User Testing"], "bio": "Pastel palettes & micro-interactions."},
    {"id": "t3", "name": "Minh Nguyen", "role": "Dev", "experience": "AI / Python Engineer",
     "tags": ["Python", "PyTorch", "Gemini API", "FastAPI"], "bio": "Smart agents; needs a React partner."},
    {"id": "t4", "name": "Chloe Chen", "role": "Biz", "experience": "Product Manager & Growth",
     "tags": ["Market Research", "Pitching", "Financial Modeling", "SaaS"], "bio": "Turns code into a venture pitch."},
    {"id": "t5", "name": "Sarah Jenkins", "role": "Design", "experience": "Creative Director",
     "tags": ["Figma", "Affinity Designer", "Motion Design", "3D Art"], "bio": "3D + CSS web storytelling."},
    {"id": "t6", "name": "Marcus Aurelius", "role": "Dev", "experience": "Mobile Developer",
     "tags": ["React Native", "Flutter", "iOS", "Android"], "bio": "Beautiful cross-platform mobile."},
]

PERKS = [
    {"id": "p1", "sponsor": "Google Gemini", "category": "AI Model", "title": "$50 Gemini API Credits",
     "value": "$50", "code": "GEMINI-HACK50", "link": "https://ai.google.dev",
     "tags": ["LLM", "Multimodal"], "description": "Free Gemini 3.5 API credits."},
    {"id": "p2", "sponsor": "Google Cloud", "category": "Cloud Credit", "title": "$300 Cloud Credits",
     "value": "$300", "code": "GCP300-HACK", "link": "https://cloud.google.com/free",
     "tags": ["Cloud Run", "Hosting"], "description": "Deploy on Cloud Run, host DBs, run GPUs."},
    {"id": "p3", "sponsor": "MongoDB Atlas", "category": "Database", "title": "$500 Atlas Credits",
     "value": "$500", "code": "MDB-ATLAS-HACK", "link": "https://www.mongodb.com/atlas",
     "tags": ["Vector Search", "RAG"], "description": "Managed MongoDB with vector search."},
    {"id": "p4", "sponsor": "Vercel", "category": "Dev Tools", "title": "Pro Plan — Free 3 Months",
     "value": "3 mo", "code": "VERCEL-PRO-3M", "link": "https://vercel.com",
     "tags": ["Deploy", "Edge"], "description": "Edge functions + instant preview deploys."},
    {"id": "p5", "sponsor": "ElevenLabs", "category": "Voice AI", "title": "Creator Tier — 3 Months",
     "value": "3 mo", "code": "11LABS-HACK", "link": "https://elevenlabs.io",
     "tags": ["Text-to-Speech", "Voice Agents"], "description": "Lifelike TTS & voice agents."},
    {"id": "p6", "sponsor": "GitHub", "category": "Dev Tools", "title": "Copilot Pro — Free 6 Months",
     "value": "6 mo", "code": "GH-COPILOT-6M", "link": "https://github.com/features/copilot",
     "tags": ["Copilot", "Codespaces"], "description": "AI pair-programmer + Codespaces."},
]

SCHEDULE = [
    {"time": "09:00 AM", "title": "Registration & Breakfast", "location": "Main Foyer (3rd Floor)",
     "description": "Check in at room 301, badges + coffee."},
    {"time": "10:00 AM", "title": "Opening Ceremony", "location": "Auditorium A",
     "description": "Keynotes + the AI Hackathon prompt."},
    {"time": "11:30 AM", "title": "Teammate Speed Dating", "location": "Grand Ballroom (East Wing)",
     "description": "Meet devs, designers, business folks."},
    {"time": "12:30 PM", "title": "Hacking Officially Starts", "location": "Grand Ballroom & Study Rooms",
     "description": "Wireframes, repo init, DB setup."},
    {"time": "02:00 PM", "title": "Gemini API Workshop", "location": "Seminar Room 302",
     "description": "GoogleGenAI, function calling, multimodal."},
    {"time": "07:00 PM", "title": "Dinner & Mentor Matchmaking", "location": "Main Dining Lounge",
     "description": "Pizza + mentor reviews."},
    {"time": "01:00 PM (Day 2)", "title": "Submission Deadline", "location": "Devpost Portal",
     "description": "Push code, submit dev URL + pitch."},
    {"time": "02:30 PM (Day 2)", "title": "Hands-on Demos & Judging", "location": "Grand Ballroom",
     "description": "3-minute demo per table."},
    {"time": "05:00 PM (Day 2)", "title": "Closing Ceremonies & Prizes", "location": "Auditorium A",
     "description": "Winners announced."},
]

# Match pool seeded into Supabase (is_seed = true). user_id uses a seed- prefix.
SEED_PROFILES = [
    {"user_id": "seed-t1", "name": "Alex Rivera", "email": "alex.rivera@example.com",
     "avatar": "https://api.dicebear.com/7.x/adventurer/svg?seed=Alex",
     "role": "Developer", "desired_role": "Designer", "domain": "AI agents",
     "skills": ["React", "TypeScript", "Node.js", "Express"], "interests": ["LLMs", "Full-stack", "Developer tools"],
     "commitment": "Serious / aiming to win", "status": "Looking for a team",
     "bio": "Fullstack dev who loves wiring LLM APIs into beautiful web apps."},
    {"user_id": "seed-t2", "name": "Susan Jones", "email": "susan@example.com",
     "avatar": "https://api.dicebear.com/7.x/lorelei/svg?seed=Susan",
     "role": "Designer", "desired_role": "Developer", "domain": "Design systems",
     "skills": ["Figma", "Prototyping", "Branding", "User Testing"], "interests": ["Micro-interactions", "Pastel UI", "Accessibility"],
     "commitment": "Serious / aiming to win", "status": "Looking for a team",
     "bio": "Senior UI/UX designer obsessed with seamless, gorgeous user journeys."},
    {"user_id": "seed-t3", "name": "Minh Nguyen", "email": "minh.n@example.com",
     "avatar": "https://api.dicebear.com/7.x/bottts/svg?seed=Minh",
     "role": "Developer", "desired_role": "Designer", "domain": "AI agents",
     "skills": ["Python", "PyTorch", "Gemini API", "FastAPI"], "interests": ["AI agents", "RAG", "Vector search"],
     "commitment": "All-in", "status": "Looking for a team",
     "bio": "AI/Python engineer building smart agents — needs a React frontend partner."},
    {"user_id": "seed-t4", "name": "Chloe Chen", "email": "chloe.c@example.com",
     "avatar": "https://api.dicebear.com/7.x/open-peeps/svg?seed=Chloe",
     "role": "Business / Pitch", "desired_role": "Developer", "domain": "FinTech",
     "skills": ["Market Research", "Pitching", "Financial Modeling", "SaaS"], "interests": ["Storytelling", "Go-to-market", "Unit economics"],
     "commitment": "Serious / aiming to win", "status": "Have a team, open to more",
     "bio": "Product/growth PM and 3x hackathon winner who turns code into a venture pitch."},
    {"user_id": "seed-t5", "name": "Sarah Jenkins", "email": "sarah.jenkins@example.com",
     "avatar": "https://api.dicebear.com/7.x/lorelei/svg?seed=Sarah",
     "role": "Designer", "desired_role": "Developer", "domain": "Interactive web",
     "skills": ["Figma", "Motion Design", "3D Art", "Affinity Designer"], "interests": ["3D web", "CSS animation", "Creative coding"],
     "commitment": "Casual / for fun", "status": "Just exploring",
     "bio": "Creative director blending 3D and smooth CSS into web storytelling."},
    {"user_id": "seed-t6", "name": "Marcus Aurelius", "email": "marcus@example.com",
     "avatar": "https://api.dicebear.com/7.x/adventurer/svg?seed=Marcus",
     "role": "Developer", "desired_role": "Business / Pitch", "domain": "Mobile games",
     "skills": ["React Native", "Flutter", "iOS", "Android"], "interests": ["Cross-platform", "Mobile games", "Native performance"],
     "commitment": "All-in", "status": "Looking for a team",
     "bio": "Ex-Meta engineer crafting beautiful cross-platform mobile experiences."},
    {"user_id": "seed-t7", "name": "Priya Sharma", "email": "priya.s@example.com",
     "avatar": "https://api.dicebear.com/7.x/adventurer/svg?seed=Priya",
     "role": "Developer", "desired_role": "Anyone complementary", "domain": "Web3",
     "skills": ["Solidity", "TypeScript", "Next.js", "Smart Contracts"], "interests": ["Web3", "DeFi", "Zero-knowledge"],
     "commitment": "Serious / aiming to win", "status": "Looking for a team",
     "bio": "Web3 engineer shipping on-chain apps; loves a strong design + pitch duo."},
    {"user_id": "seed-t8", "name": "Diego Lopez", "email": "diego.l@example.com",
     "avatar": "https://api.dicebear.com/7.x/open-peeps/svg?seed=Diego",
     "role": "Business / Pitch", "desired_role": "Designer", "domain": "AI agents",
     "skills": ["Pitching", "Growth", "User Research", "Notion"], "interests": ["AI agents", "Storytelling", "B2B SaaS"],
     "commitment": "Serious / aiming to win", "status": "Looking for a team",
     "bio": "Growth-minded pitcher who frames AI prototypes as fundable products."},
]
