"""Server-side mock data mirroring src/mockData.ts.

- TEAMMATES / PERKS / SCHEDULE are embedded into the agent system prompts so the model
  references real IDs (the frontend renders them by ID from src/mockData.ts).
- SEED_PROFILES are the 8 candidate profiles seeded into Supabase as the match pool.
"""

TEAMMATES = [
    {"id": "t1", "name": "Alex Rivera", "role": "Dev", "experience": "Fullstack Developer",
     "tags": ["React", "TypeScript", "Node.js", "Express"], "bio": "Fullstack web + LLM APIs."},
    {"id": "t2", "name": "Susan Jones", "role": "Design", "experience": "Senior UI/UX Designer",
     "tags": ["Figma", "Prototyping", "Branding", "User Testing"], "bio": "Pastel palettes & micro-interactions."},
    {"id": "t3", "name": "Minh Nguyen", "role": "Dev", "experience": "AI / Python Engineer",
     "tags": ["Python", "PyTorch", "Gemini API", "FastAPI"], "bio": "Smart agents; needs a React partner."},
    {"id": "t4", "name": "Chloe Chen", "role": "Biz", "experience": "Product Manager & Growth",
     "tags": ["Market Research", "Pitching", "Financial Modeling", "SaaS"], "bio": "Turns code into a venture pitch."},
    {"id": "t5", "name": "Sarah Jenkins", "role": "Design", "experience": "Creative Director",
     "tags": ["Figma", "Affinity Designer", "Motion Design", "3D Art"], "bio": "3D + CSS web storytelling."},
    {"id": "t6", "name": "Marcus Aurelius", "role": "Dev", "experience": "Mobile Developer",
     "tags": ["React Native", "Flutter", "iOS", "Android"], "bio": "Beautiful cross-platform mobile."},
]

PERKS = [
    {"id": "p1", "sponsor": "Google Gemini", "category": "AI Model", "title": "$50 Gemini API Credits",
     "value": "$50", "code": "GEMINI-HACK50", "link": "https://ai.google.dev",
     "tags": ["LLM", "Multimodal"], "description": "Free Gemini 3.5 API credits."},
    {"id": "p2", "sponsor": "Google Cloud", "category": "Cloud Credit", "title": "$300 Cloud Credits",
     "value": "$300", "code": "GCP300-HACK", "link": "https://cloud.google.com/free",
     "tags": ["Cloud Run", "Hosting"], "description": "Deploy on Cloud Run, host DBs, run GPUs."},
    {"id": "p3", "sponsor": "MongoDB Atlas", "category": "Database", "title": "$500 Atlas Credits",
     "value": "$500", "code": "MDB-ATLAS-HACK", "link": "https://www.mongodb.com/atlas",
     "tags": ["Vector Search", "RAG"], "description": "Managed MongoDB with vector search."},
    {"id": "p4", "sponsor": "Vercel", "category": "Dev Tools", "title": "Pro Plan — Free 3 Months",
     "value": "3 mo", "code": "VERCEL-PRO-3M", "link": "https://vercel.com",
     "tags": ["Deploy", "Edge"], "description": "Edge functions + instant preview deploys."},
    {"id": "p5", "sponsor": "ElevenLabs", "category": "Voice AI", "title": "Creator Tier — 3 Months",
     "value": "3 mo", "code": "11LABS-HACK", "link": "https://elevenlabs.io",
     "tags": ["Text-to-Speech", "Voice Agents"], "description": "Lifelike TTS & voice agents."},
    {"id": "p6", "sponsor": "GitHub", "category": "Dev Tools", "title": "Copilot Pro — Free 6 Months",
     "value": "6 mo", "code": "GH-COPILOT-6M", "link": "https://github.com/features/copilot",
     "tags": ["Copilot", "Codespaces"], "description": "AI pair-programmer + Codespaces."},
]

SCHEDULE = [
    {"time": "09:00 AM", "title": "Registration & Breakfast", "location": "Main Foyer (3rd Floor)",
     "description": "Check in at room 301, badges + coffee."},
    {"time": "10:00 AM", "title": "Opening Ceremony", "location": "Auditorium A",
     "description": "Keynotes + the AI Hackathon prompt."},
    {"time": "11:30 AM", "title": "Teammate Speed Dating", "location": "Grand Ballroom (East Wing)",
     "description": "Meet devs, designers, business folks."},
    {"time": "12:30 PM", "title": "Hacking Officially Starts", "location": "Grand Ballroom & Study Rooms",
     "description": "Wireframes, repo init, DB setup."},
    {"time": "02:00 PM", "title": "Gemini API Workshop", "location": "Seminar Room 302",
     "description": "GoogleGenAI, function calling, multimodal."},
    {"time": "07:00 PM", "title": "Dinner & Mentor Matchmaking", "location": "Main Dining Lounge",
     "description": "Pizza + mentor reviews."},
    {"time": "01:00 PM (Day 2)", "title": "Submission Deadline", "location": "Devpost Portal",
     "description": "Push code, submit dev URL + pitch."},
    {"time": "02:30 PM (Day 2)", "title": "Hands-on Demos & Judging", "location": "Grand Ballroom",
     "description": "3-minute demo per table."},
    {"time": "05:00 PM (Day 2)", "title": "Closing Ceremonies & Prizes", "location": "Auditorium A",
     "description": "Winners announced."},
]

# Match pool seeded into Supabase (is_seed = true). user_id uses a seed- prefix.
# Sample data exercises every expanded profile field so matching + the UI have
# realistic content across roles, tracks and event-partner AI tools.
SEED_PROFILES = [
    {"user_id": "seed-t1", "name": "Alex Rivera", "email": "alex.rivera@example.com",
     "avatar": "https://api.dicebear.com/7.x/adventurer/svg?seed=Alex",
     "linkedin": "https://linkedin.com/in/alex-rivera-hack", "github": "https://github.com/alexrivera",
     "portfolio": "https://alexrivera.dev",
     "role": "Developer", "ai_ml_experience": "1–2 years", "agentic_experience": "Intermediate",
     "hackathon_count": "4–5 times", "english_level": "Fluent",
     "desired_role": "Frontend", "tracks": ["F&B Track", "Retail Track"], "domain": "AI agents",
     "skills": ["TypeScript", "JavaScript", "Python"], "frameworks": ["React", "Next.js", "FastAPI"],
     "ai_tools": ["OpenAI", "n8n", "Vercel AI SDK"], "tech_stack": ["Next.js", "Supabase", "Vercel"],
     "interests": ["LLMs", "Full-stack", "Developer tools"],
     "idea_stage": "Rough idea", "idea_description": "An AI menu recommender that personalizes restaurant orders.",
     "commitment": "Serious / aiming to win", "status": "Looking for a team"},
    {"user_id": "seed-t2", "name": "Susan Jones", "email": "susan@example.com",
     "avatar": "https://api.dicebear.com/7.x/lorelei/svg?seed=Susan",
     "linkedin": "https://linkedin.com/in/susan-jones-ux", "github": "", "portfolio": "https://dribbble.com/susanjones",
     "role": "Other", "ai_ml_experience": "< 1 year", "agentic_experience": "Beginner",
     "hackathon_count": "2–3 times", "english_level": "Native",
     "desired_role": "UI/UX Designer", "tracks": ["Gaming Track"], "domain": "Design systems",
     "skills": ["JavaScript"], "frameworks": ["React", "Tailwind"],
     "ai_tools": ["Midjourney", "OpenAI"], "tech_stack": ["Figma", "Framer"],
     "interests": ["Micro-interactions", "Pastel UI", "Accessibility"],
     "idea_stage": "Looking for a team with an idea", "idea_description": "",
     "commitment": "Serious / aiming to win", "status": "Looking for a team"},
    {"user_id": "seed-t3", "name": "Minh Nguyen", "email": "minh.n@example.com",
     "avatar": "https://api.dicebear.com/7.x/bottts/svg?seed=Minh",
     "linkedin": "https://linkedin.com/in/minh-nguyen-ai", "github": "https://github.com/minhnguyen-ai",
     "portfolio": "",
     "role": "AI Engineer", "ai_ml_experience": "3–5 years", "agentic_experience": "Advanced",
     "hackathon_count": "6+ times", "english_level": "Conversational",
     "desired_role": "AI/Data Engineer", "tracks": ["Mobility Track"], "domain": "AI agents",
     "skills": ["Python", "TypeScript"], "frameworks": ["PyTorch", "FastAPI", "LangChain"],
     "ai_tools": ["Qwen", "Hugging Face", "AWS", "OpenAI"], "tech_stack": ["FastAPI", "pgvector", "AWS"],
     "interests": ["AI agents", "RAG", "Vector search"],
     "idea_stage": "Have a concrete idea", "idea_description": "A multi-agent route planner for last-mile delivery.",
     "commitment": "All-in 🚀", "status": "Looking for a team"},
    {"user_id": "seed-t4", "name": "Chloe Chen", "email": "chloe.c@example.com",
     "avatar": "https://api.dicebear.com/7.x/open-peeps/svg?seed=Chloe",
     "linkedin": "https://linkedin.com/in/chloe-chen-biz", "github": "", "portfolio": "https://chloechen.co",
     "role": "Founder", "ai_ml_experience": "< 1 year", "agentic_experience": "Beginner",
     "hackathon_count": "4–5 times", "english_level": "Fluent",
     "desired_role": "Business Pitcher", "tracks": ["Retail Track"], "domain": "FinTech / Retail",
     "skills": ["SQL"], "frameworks": [],
     "ai_tools": ["OpenAI", "n8n"], "tech_stack": ["Notion", "Airtable"],
     "interests": ["Storytelling", "Go-to-market", "Unit economics"],
     "idea_stage": "Rough idea", "idea_description": "AI loyalty assistant that boosts repeat retail purchases.",
     "commitment": "Serious / aiming to win", "status": "Have a team, open to more"},
    {"user_id": "seed-t5", "name": "Sarah Jenkins", "email": "sarah.jenkins@example.com",
     "avatar": "https://api.dicebear.com/7.x/lorelei/svg?seed=Sarah",
     "linkedin": "https://linkedin.com/in/sarah-j-design", "github": "", "portfolio": "https://sarahjenkins.art",
     "role": "Other", "ai_ml_experience": "None", "agentic_experience": "None",
     "hackathon_count": "First time", "english_level": "Native",
     "desired_role": "UI/UX Designer", "tracks": ["Aviation Track"], "domain": "Interactive web",
     "skills": ["JavaScript"], "frameworks": ["Three.js", "GSAP"],
     "ai_tools": ["Midjourney", "Runway"], "tech_stack": ["Figma", "Blender"],
     "interests": ["3D web", "CSS animation", "Creative coding"],
     "idea_stage": "No idea yet", "idea_description": "",
     "commitment": "Casual / for fun", "status": "Just exploring"},
    {"user_id": "seed-t6", "name": "Marcus Aurelius", "email": "marcus@example.com",
     "avatar": "https://api.dicebear.com/7.x/adventurer/svg?seed=Marcus",
     "linkedin": "https://linkedin.com/in/marcus-native", "github": "https://github.com/marcusaurelius-dev",
     "portfolio": "",
     "role": "Developer", "ai_ml_experience": "1–2 years", "agentic_experience": "Intermediate",
     "hackathon_count": "6+ times", "english_level": "Fluent",
     "desired_role": "Frontend", "tracks": ["Gaming Track"], "domain": "Mobile games",
     "skills": ["Dart", "Swift", "Kotlin"], "frameworks": ["React Native", "Flutter"],
     "ai_tools": ["OpenAI", "AWS"], "tech_stack": ["Flutter", "Firebase", "AWS"],
     "interests": ["Cross-platform", "Mobile games", "Native performance"],
     "idea_stage": "Rough idea", "idea_description": "An AI game master that generates live mobile quests.",
     "commitment": "All-in 🚀", "status": "Looking for a team"},
    {"user_id": "seed-t7", "name": "Priya Sharma", "email": "priya.s@example.com",
     "avatar": "https://api.dicebear.com/7.x/adventurer/svg?seed=Priya",
     "linkedin": "https://linkedin.com/in/priya-sharma-web3", "github": "https://github.com/priyasharma",
     "portfolio": "https://priya.build",
     "role": "Developer", "ai_ml_experience": "1–2 years", "agentic_experience": "Intermediate",
     "hackathon_count": "2–3 times", "english_level": "Fluent",
     "desired_role": "Backend", "tracks": ["Real Estate Track"], "domain": "PropTech / Web3",
     "skills": ["TypeScript", "Python", "Solidity"], "frameworks": ["Next.js", "FastAPI"],
     "ai_tools": ["OpenAI", "Qwen", "AWS"], "tech_stack": ["Next.js", "Postgres", "AWS"],
     "interests": ["Web3", "PropTech", "Automation"],
     "idea_stage": "Looking for a team with an idea", "idea_description": "",
     "commitment": "Serious / aiming to win", "status": "Looking for a team"},
    {"user_id": "seed-t8", "name": "Diego Lopez", "email": "diego.l@example.com",
     "avatar": "https://api.dicebear.com/7.x/open-peeps/svg?seed=Diego",
     "linkedin": "https://linkedin.com/in/diego-lopez-growth", "github": "", "portfolio": "https://diegolopez.io",
     "role": "Founder", "ai_ml_experience": "None", "agentic_experience": "Beginner",
     "hackathon_count": "4–5 times", "english_level": "Fluent",
     "desired_role": "Product Manager", "tracks": ["F&B Track"], "domain": "AI agents / F&B",
     "skills": [], "frameworks": [],
     "ai_tools": ["n8n", "OpenAI"], "tech_stack": ["Notion", "Zapier"],
     "interests": ["AI agents", "Storytelling", "B2B SaaS"],
     "idea_stage": "Have a concrete idea", "idea_description": "An AI ops copilot that automates restaurant supply orders.",
     "commitment": "Serious / aiming to win", "status": "Looking for a team"},
]
